### ISSUE TITLE
Adding extra parameters to company get request

### ISSUE THREAD

**Issue by DaanGeurts** [SynergiTech/creditsafe-connect#20]
Hi, 
thanks for all the hard work!
I have a question, when getting a German report one should provide 
/companies/{id}?customData=de_reason_code::{reasonCode} the reason code for legal purposes.
[Documentation](https://creditsafe.freshdesk.com/en/support/solutions/articles/7000052620-what-to-do-if-you-see-german-reports-require-a-reason-code-)
using companies()->get($companyId, $language), is there any method to provide this customData property?

**Comment by willpower232** [comment]
Thanks for your interest.

I don't think there is a way of specifying it currently but if you're able to make a PR to add in an optional array of extra fields to the `get` function which gets merged into the array which contains language then we can get that released for you

https://github.com/SynergiTech/creditsafe-connect/blob/65a29f14b3e593179c8cb4c4bca87d7cac13ae11/src/Service/CompanyService.php#L43-L45

**Comment by DaanGeurts** [comment]
Hi Will,

I found this PR https://github.com/SynergiTech/creditsafe-connect/pull/8
But it's not merged due to linting and formatting...

**Comment by willpower232** [comment]
Ah so it is, well they clearly have no intent on completing it.

The change I described above is only two lines worth of change so would be a much simpler and future proof solution if you have some time to work on it?

**Comment by DaanGeurts** [comment]
Yes it could be a simple addition but there is more to it as you can read from the documentation. There is an extra endpoint to fetch all the available reason codes per country.
If you agree with a array merge of params and not adding the endpoint etc I'm more then happy to create a pull request

**Comment by willpower232** [comment]
Of course, if you want to grab and maybe improve src/Service/ReportCustomData.php from that PR as part of yours then that is probably a complete solution.

**Comment by DaanGeurts** [comment]
Are you happy with the structure and code of the PR as I can copy that for my PR?

**Comment by willpower232** [comment]
if the linter is happy with you then it should be fine, that PR seemed to change a lot of code that wasn't related to the original issue and, whilst probably necessary at some point, really confused the issue :sweat_smile:

**Comment by DaanGeurts** [comment]
Hi Will,
i've created a new pull request based of the pull request mentioned here.
Let me know!

**Comment by willpower232** [comment]
Looks great to me, I've released it so feel free to close if you have no more issues on this topic
